name: 'POC Docker Helm Helper'
branding:
  icon: 'archive'
  color: 'green'
inputs:
  container_registry:
    description: 'Endereço do Docker Container Registry'
    required: true
  chart_source_location:
    description: 'Diretório do Helm desse repositório'
    required: false
    default: 'infrastructure/helm'
  environment:
    description: 'Ambiente alvo'
    required: true
outputs:
  tag:
    description: 'Tag do commit'
  version:
    description: 'Versão baseada na tag'
  short_sha:
    description: 'Short sha'
  project_slug:
    description: 'URI do projeto'
  container_registry:
    description: 'Endereço do Docker Container Registry'
  container_image:
    description: 'Endereço do Docker Container Registry com repositório e tag'
  chart_source_location:
    description: 'Diretório do Helm desse repositório'
  chart_target_location:
    description: 'Diretório do Helm'
  environment:
    description: 'Ambiente alvo'
runs:
  using: 'node12'
  main: 'dist/index.js'
